### ISSUE TITLE
Message prompt UI is not responsive in Google Chrome 44

### ISSUE THREAD

**Issue by mattijas** [Financial-Times/n-message-prompts#29]
Given that I see the message prompt in my browser window,
When I resize my browser to make the view port narrower than the size of the prompt,
[expected] Then the message prompt switches to the small screen version.

[actual, Win 7/Chrome v44] Then the large message prompts remains visible even though it doesn't fit the viewport.

https://files.slack.com/files-pri/T025C95MN-F09LJ9M7U/pasted_image_at_2015_08_26_13_53.png

**Comment by ifyio** [comment]
On windows

**Comment by ifyio** [comment]
This should be fixed now
