### ISSUE TITLE
Message Prompt - "Save 25% now" CTA

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/n-message-prompts#4]
Can this link to the PSP (product selector page)

![image](https://cloud.githubusercontent.com/assets/8235225/9410941/0e662878-481b-11e5-8efa-3ffe43ee53cf.png)

**Comment by ifyio** [comment]
@SarahHornsey, so I guess both the 'LIMITED OFFER' and the 'SAVE 25% NOW' buttons should link to the PSP?

**Comment by ifyio** [comment]
Ok I just saw that limited offer shouldn't be a button

**Comment by SarahHornsey** [comment]
No, just the 'SAVE 25% NOW' button. Thanks

**Comment by ifyio** [comment]
Just a note to self. I will need the `segId` here
