### ISSUE TITLE
B2B message prompt

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/n-message-prompts#48]
https://drive.google.com/a/ft.com/file/d/0B8039_pUsjqtNERCV0F3OUtkUjA/view?usp=sharing

https://drive.google.com/a/ft.com/file/d/0B8039_pUsjqtOEpyeF8xNDZEcGs/view?usp=sharing

**Comment by ifyio** [comment]
Moved the contents into #39 and closing this
