### ISSUE TITLE
This module needs CI

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/n-message-prompts#65]
Please set up :)

Probably just needs `n-message-prompts: component()` adding to this file:-
http://git.svc.ft.com:8080/projects/NEXTPRIVATE/repos/config-vars/browse/models/continuous-integration.js

**Comment by adambraimbridge** [comment]
https://github.com/Financial-Times/next-config-vars/blob/master/models/continuous-integration.js#L94
